apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: skaffold-tut
build:
  artifacts:
    - image: creation00/skaffold-node
      docker:
        dockerfile: Dockerfile
test:
- image: creation00/skaffold-node
  custom:
    - command: npm run test
manifests:
  rawYaml:
    - k8s/web.yaml
