apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: skaffold-tut
build:
  artifacts:
    - image: skaffold-node
      context: ./backend
      docker:
        dockerfile: Dockerfile
test:
- image: skaffold-node
  context: ./backend
  custom:
    - command: npm run test
manifests:
  rawYaml:
    - k8s/web.yaml
portForward:
- resourceType: Service
  resourceName: web
  port: 3000
  address: 127.0.0.1
  localPort: 8080
