apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: skaffold-tut
build:
  tagPolicy:
    inputDigest: {}
  artifacts:
    - image: creation00/skaffold-node
      docker:
        dockerfile: Dockerfile
  local:
    push: true
test:
- image: creation00/skaffold-node
  custom:
    - command: npm run test
manifests:
  rawYaml:
    - k8s-dev/web.yaml
