apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: skaffold-tut
build:
  artifacts:
    - image: skaffold-node
      context: ./backend
      docker:
        dockerfile: Dockerfile
test:
- image: skaffold-node
  context: ./backend
  custom:
    - command: npm run test
manifests:
  rawYaml:
    - k8s/web.yaml
